# Generated by Django 5.1 on 2024-08-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie',
            field=models.FileField(default=3, upload_to='video/'),
            preserve_default=False,
        ),
    ]
