# Generated by Django 5.1 on 2024-08-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0002_movies_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie',
            field=models.FileField(upload_to='movies/'),
        ),
    ]
