# Generated by Django 5.1 on 2024-10-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0004_alter_subscription_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ott_user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
