# Generated by Django 5.1 on 2025-01-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0006_remove_ott_user_u_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Thumbnail',
            field=models.ImageField(null=True, upload_to='movies/thumbnails/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
