# Generated by Django 5.1 on 2025-01-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0008_alter_ott_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
