# Generated by Django 5.1 on 2025-01-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0009_alter_movies_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Thumbnail',
            field=models.ImageField(upload_to='movies/thumbnails/'),
        ),
    ]
