# Generated by Django 5.1 on 2025-01-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0010_alter_movies_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='content_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show')], default='Movie', max_length=10),
        ),
    ]
